#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Tue Feb 11 15:24:22 +03 2025
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/eciftci/Xilinx/Vivado/2024.2/data"

# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -L axi_vip_v1_1_20 -L smartconnect_v1_0 -L xilinx_vip -prj microblazev_wrapper_vlog.prj"
xvlog --incr --relax -L uvm -L axi_vip_v1_1_20 -L smartconnect_v1_0 -L xilinx_vip -prj microblazev_wrapper_vlog.prj 2>&1 | tee compile.log

# compile VHDL design sources
echo "xvhdl --incr --relax -prj microblazev_wrapper_vhdl.prj"
xvhdl --incr --relax -prj microblazev_wrapper_vhdl.prj 2>&1 | tee -a compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
