#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Feb 11 15:24:26 +03 2025
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/eciftci/Xilinx/Vivado/2024.2/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L microblaze_v11_0_14 -L microblaze_riscv_v1_0_4 -L lmb_v10_v3_0_14 -L lmb_bram_if_cntlr_v4_0_25 -L blk_mem_gen_v8_4_10 -L axi_lite_ipif_v3_0_4 -L mdm_riscv_v1_0_4 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L lib_pkg_v1_0_4 -L lib_srl_fifo_v1_0_4 -L axi_uartlite_v2_0_38 -L xlconstant_v1_1_9 -L smartconnect_v1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_34 -L axi_vip_v1_1_20 -L axi_intc_v4_1_20 -L xlconcat_v2_1_6 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot microblazev_wrapper_behav xil_defaultlib.microblazev_wrapper xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L microblaze_v11_0_14 -L microblaze_riscv_v1_0_4 -L lmb_v10_v3_0_14 -L lmb_bram_if_cntlr_v4_0_25 -L blk_mem_gen_v8_4_10 -L axi_lite_ipif_v3_0_4 -L mdm_riscv_v1_0_4 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L lib_pkg_v1_0_4 -L lib_srl_fifo_v1_0_4 -L axi_uartlite_v2_0_38 -L xlconstant_v1_1_9 -L smartconnect_v1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_34 -L axi_vip_v1_1_20 -L axi_intc_v4_1_20 -L xlconcat_v2_1_6 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot microblazev_wrapper_behav xil_defaultlib.microblazev_wrapper xil_defaultlib.glbl -log elaborate.log

